name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-bot:
    name: brew test-bot (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cleanup before
        run: brew test-bot --only-cleanup-before-fork

      - name: Tap syntax
        run: brew test-bot --only-tap-syntax

      - name: Build & test all formulae
        run: brew test-bot --only-formulae

      - name: Cleanup after
        if: always()
        run: brew test-bot --only-cleanup-after-fork

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.os }}
          path: |
            ~/Library/Logs/Homebrew/**/*
            /home/linuxbrew/.linuxbrew/var/log/**/*
